#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}


check() {
  config::load_file $SERVICE_GRAFANA_CONFIG

  if [ ! -f "${SERVICE_CONFIGS}/config.ini" ]; then
    cp ${SERVICE_DIR}/conf/config.ini ${SERVICE_CONFIGS}/config.ini
  fi

  service::config_set SERVICE_GRAFANA_ROOT_URL text "Root URL"

  # service::config_set SERVICE_QDRANT_PORT text "Port" 8024
  service::config_set SERVICE_GRAFANA_DOREAMON_CLIENT_ID text "Doreamon Client ID"
  service::config_set SERVICE_GRAFANA_DOREAMON_CLIENT_SECRET text "Doreamon Client Secret"
}

check $@
""
